name: Publisher

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:     
    runs-on: ubuntu-latest
    
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack p1eXu5.AspNetCore.Testing
      run: dotnet pack --no-build --configuration Release src/p1eXu5.AspNetCore.Testing/p1eXu5.AspNetCore.Testing.csproj --output .
      
    - name: Login GitHub Nuget Repo
      run: dotnet nuget add source --username p1eXu5 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/p1eXu5/index.json"

    - name: Push p1eXu5.AspNetCore.Testing Nuget
      run: dotnet nuget push p1eXu5.AspNetCore.Testing.*.nupkg --source github --skip-duplicate
